"""
Django settings for bandaskapp project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-6nyix5o5ot7jnu@kvnh)dlkke_^s!+*)2kh55vaz)(bb(xr+o4"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "core",
    "hardware",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "bandaskapp.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "bandaskapp.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# BandaskApp Configuration
BANDASKAPP_CONFIG = {
    # Thermometer Configuration - Array-based approach
    'THERMOMETERS': [
        {
            'id': '28AA8C7F481401C8',  # Circuit ID
            'label': 'DHW Top',        # Display label (NONE = not shown)
            'color': '#ff6b6b'         # UI color
        },
        {
            'id': '2896A9340A0000F1',
            'label': 'DHW Middle', 
            'color': '#ffa500'
        },
        {
            'id': '28AA9A5948140151',
            'label': 'HHW Top',
            'color': '#ffa500'
        },
        {
            'id': '28AA26EC47140170',
            'label': 'HHW Bottom',
            'color': '#ff6b6b'
        },
        {
            'id': '28AAB01B481401F3',
            'label': 'Furnace hot',           # Not shown in UI
            'color': '#ff6b6b'
        },
        {
            'id': '28EBDE49F6AF3CF7',
            'label': 'Heating radiator',           # Not shown in UI
            'color': '#ff6b6b'
        },
        {
            'id': '28AA7EE147140146',
            'label': 'Heating floor',           # Not shown in UI
            'color': '#ff6b6b'
        }
    ],
    'FURNACE_RELAY_ID': '1_01',  # Furnace relay circuit ID
    'PUMP_RELAY_ID': '1_02',  # Pump relay circuit ID
    'HEATING_CONTROL_UNIT_ID': '1_01',  # Heating control unit digital input circuit ID

    'EVOK_BASE_URL': 'http://127.0.0.1:8080',  # EVOK API base URL
    'UPDATE_INTERVAL': 5,  # Monitoring loop interval in seconds
    'COOLDOWN_TIMES': {
        'furnace': 30,  # Furnace relay cooldown in seconds
        'pump': 5,  # Pump relay cooldown in seconds
    },
    'TEMPERATURE_VALIDATION': {
        'min_temp': 0.0,  # Minimum valid temperature
        'max_temp': 100.0,  # Maximum valid temperature
        'max_jump': 20.0,  # Maximum temperature jump per update
    },
    'DHW_THRESHOLDS': {
        'low': 45.0,  # DHW low temperature threshold
        'high': 60.0,  # DHW high temperature threshold
    },
    'HHW_THRESHOLDS': {
        'low': 45.0,  # HHW low temperature threshold (initially same as DHW)
        'high': 60.0,  # HHW high temperature threshold (initially same as DHW)
    },
    
    # Control Circuit Configuration
    'CONTROL_DHW_ID': '2896A9340A0000F1',  # Control temperature sensor for DHW (same as THERMOMETER_DHW_1_ID)
    'CONTROL_HHW_ID': '2896A9340A0000F1',  # Control temperature sensor for HHW (same as THERMOMETER_HHW_1_ID)
}
