# Generated by Django 4.2.7 on 2025-08-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemstate",
            name="hhw_temp_high",
            field=models.FloatField(
                default=60.0, help_text="HHW high temperature threshold (°C)"
            ),
        ),
        migrations.AddField(
            model_name="systemstate",
            name="hhw_temp_low",
            field=models.FloatField(
                default=45.0, help_text="HHW low temperature threshold (°C)"
            ),
        ),
        migrations.AddField(
            model_name="systemstate",
            name="winter_regime_state",
            field=models.CharField(
                choices=[
                    ("off", "Summer Regime (DHW Only)"),
                    ("automatic", "Winter Regime (Automatic)"),
                    ("on", "Winter Regime (Manual)"),
                ],
                default="automatic",
                help_text="Winter regime state",
                max_length=20,
            ),
        ),
    ]
